# Generated by Django 4.0.6 on 2022-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_end',
            field=models.TimeField(verbose_name='Time of the end of the mailing list'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_start',
            field=models.TimeField(verbose_name='Time of the newsletter launch'),
        ),
    ]
